"use client";
import React, { useState } from "react";
import {
  Download,
  FileSpreadsheet,
  Layers,
  Truck,
  History,
  AlertTriangle,
  Loader2
} from "lucide-react";
import { AppShell } from "@/app/components/layout/AppShell";
import { downloadFile, getLatestMaster } from "@/lib/api";

type ReportKind = "download" | "latest-master";

interface ReportDef {
  id: string;
  title: string;
  desc: string;
  format: string;
  kind: ReportKind;
  endpoint: string;
  filename: string;
  icon: React.ReactNode;
}

const REPORTS: ReportDef[] = [
  {
    id: "wip-csv",
    title: "Stage-Wise WIP Matrix Report",
    desc: "Complete snapshot of part balances held across all stages (F1 through Dispatch) per Work Order.",
    format: "CSV",
    kind: "download",
    endpoint: "/api/v1/reports/export/wip-csv",
    filename: "vspl_smes_wip_report.csv",
    icon: <Layers className="h-5 w-5 text-blue-500" />,
  },
  {
    id: "movements-csv",
    title: "Production Movements Ledger",
    desc: "Full immutable physical movement audit trail including operator, machine, shift, and quantity.",
    format: "CSV",
    kind: "download",
    endpoint: "/api/v1/reports/export/movements-csv",
    filename: "vspl_smes_movement_ledger.csv",
    icon: <History className="h-5 w-5 text-emerald-500" />,
  },
  {
    id: "dispatch-csv",
    title: "Dispatch & Invoices Register",
    desc: "Detailed record of customer dispatches, invoice numbers, vehicle details, and shipping dates.",
    format: "CSV",
    kind: "download",
    endpoint: "/api/v1/reports/export/dispatch-csv",
    filename: "vspl_smes_dispatch_report.csv",
    icon: <Truck className="h-5 w-5 text-purple-500" />,
  },
  {
    id: "master-xlsx",
    title: "Latest OMS Master Spreadsheet",
    desc: "Reconciled Master Workbook generated by the deterministic OMS Engine v3.3.",
    format: "XLSX",
    kind: "latest-master",
    endpoint: "",
    filename: "",
    icon: <FileSpreadsheet className="h-5 w-5 text-emerald-600" />,
  },
];

export default function ReportsCenterPage() {
  const [busyId, setBusyId] = useState<string | null>(null);
  const [errors, setErrors] = useState<Record<string, string>>({});

  async function handleDownload(report: ReportDef) {
    setBusyId(report.id);
    setErrors((prev) => ({ ...prev, [report.id]: "" }));
    try {
      if (report.kind === "latest-master") {
        const latest = await getLatestMaster();
        if (!latest?.latest_master) {
          setErrors((prev) => ({
            ...prev,
            [report.id]: "No master spreadsheet has been generated yet. Run an OMS Engine cycle first.",
          }));
          return;
        }
        await downloadFile(
          `/api/v1/oms/download/master/${encodeURIComponent(latest.latest_master)}`,
          latest.latest_master
        );
      } else {
        await downloadFile(report.endpoint, report.filename);
      }
    } catch (err: any) {
      setErrors((prev) => ({
        ...prev,
        [report.id]: err?.response?.data?.detail || "Report download failed. Please try again.",
      }));
    } finally {
      setBusyId(null);
    }
  }

  return (
    <AppShell>
      <div className="max-w-4xl mx-auto space-y-6">
        {/* Header */}
        <div>
          <div className="flex items-center gap-2">
            <span className="rounded-md bg-blue-600 px-2 py-0.5 text-[10px] font-bold text-white uppercase tracking-wider">
              Data & Analytics
            </span>
            <span className="text-xs text-zinc-400">Enterprise Reports</span>
          </div>
          <h1 className="text-2xl font-extrabold tracking-tight text-zinc-900 dark:text-zinc-50 mt-1">
            Manufacturing Reports Center
          </h1>
          <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-0.5">
            Export standardized compliance, WIP buffer, stage movement, and dispatch registers for plant management.
          </p>
        </div>

        {/* Reports Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {REPORTS.map((r) => (
            <div
              key={r.id}
              className="flex flex-col justify-between rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-5 shadow-sm hover:shadow-md transition-all"
            >
              <div>
                <div className="flex items-center justify-between">
                  <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-zinc-100 dark:bg-zinc-800">
                    {r.icon}
                  </div>
                  <span className="rounded-md bg-zinc-100 dark:bg-zinc-800 px-2 py-0.5 text-[10px] font-mono font-bold uppercase text-zinc-600 dark:text-zinc-400">
                    {r.format}
                  </span>
                </div>

                <h3 className="text-sm font-bold text-zinc-900 dark:text-zinc-100 mt-3">
                  {r.title}
                </h3>
                <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-1 leading-relaxed">
                  {r.desc}
                </p>

                {errors[r.id] && (
                  <div className="mt-2 flex items-start gap-1.5 rounded-lg bg-rose-50 dark:bg-rose-950/40 px-2.5 py-1.5 text-[11px] font-medium text-rose-600 dark:text-rose-400">
                    <AlertTriangle className="h-3.5 w-3.5 shrink-0 mt-0.5" />
                    <span>{errors[r.id]}</span>
                  </div>
                )}
              </div>

              <div className="pt-4 mt-4 border-t border-zinc-100 dark:border-zinc-800 flex justify-end">
                <button
                  type="button"
                  onClick={() => handleDownload(r)}
                  disabled={busyId === r.id}
                  className="flex items-center gap-1.5 rounded-xl bg-blue-600 px-4 py-2 text-xs font-bold text-white shadow-xs hover:bg-blue-500 disabled:opacity-60 disabled:cursor-not-allowed transition-colors cursor-pointer"
                >
                  {busyId === r.id ? (
                    <Loader2 className="h-3.5 w-3.5 animate-spin" />
                  ) : (
                    <Download className="h-3.5 w-3.5" />
                  )}
                  <span>{busyId === r.id ? "Preparing…" : "Download Report"}</span>
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </AppShell>
  );
}
