"""init

Revision ID: c0b74e652600
Revises: 
Create Date: 2026-08-06 21:21:21.732096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0b74e652600'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_code')
    )
    op.create_table('parts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_number')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CEO', 'PRODUCTION_MANAGER', 'PLANNER', 'QA', 'DISPATCH', 'MACHINE_OPERATOR', 'STORE', 'SALES', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('customer_po', sa.String(), nullable=False),
    sa.Column('po_qty', sa.Integer(), nullable=False),
    sa.Column('max_batch_size', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACCEPT', 'HOLD', 'REJECT', name='orderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wo_number', sa.String(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('physical_wo_qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ON_TRACK', 'AT_RISK', 'OVERDUE', 'CLOSED', name='wostatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wo_number')
    )
    op.create_table('conversions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_wo_id', sa.UUID(), nullable=False),
    sa.Column('destination_order_id', sa.UUID(), nullable=False),
    sa.Column('conversion_wo_id', sa.UUID(), nullable=False),
    sa.Column('entry_stage', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversion_wo_id'], ['work_orders.id'], ),
    sa.ForeignKeyConstraint(['destination_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['source_wo_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispatches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_order_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('dispatched_qty', sa.Integer(), nullable=False),
    sa.Column('dispatch_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('nc_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nc_number', sa.String(), nullable=False),
    sa.Column('work_order_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('defect_code', sa.String(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('root_cause', sa.String(), nullable=True),
    sa.Column('disposition', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nc_number')
    )
    op.create_table('production_updates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_order_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('F1', 'F2', 'F3', 'SP', 'FI', 'BSR', 'DISPATCH', name='stagecode'), nullable=False),
    sa.Column('machine', sa.String(), nullable=True),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('shift', sa.String(), nullable=True),
    sa.Column('good_qty', sa.Integer(), nullable=True),
    sa.Column('reject_qty', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', name='productionstatus'), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wo_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_order_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('F1', 'F2', 'F3', 'SP', 'FI', 'BSR', 'DISPATCH', name='stagecode'), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('stage_target_qty', sa.Integer(), nullable=False),
    sa.Column('cumulative_ok_qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wo_routes')
    op.drop_table('production_updates')
    op.drop_table('nc_records')
    op.drop_table('dispatches')
    op.drop_table('conversions')
    op.drop_table('work_orders')
    op.drop_table('orders')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('parts')
    op.drop_table('customers')
    # ### end Alembic commands ###
